### ISSUE TITLE
Update email not always syncing

### ISSUE THREAD

**Issue by splendidrob** [craftcms/stripe#12]
### Description
Odd one here - changin a users email address only seems to sometimes sync with stripe

### Steps to reproduce

1. Change a users email address in Craft and notice it updates in Stripe
2. Change it back again and it doesnt update in Stripe.
3. Changing it again sometimes seems to result in a synced change but I cant see any reason why

### Additional info

- Craft version: Craft Pro 5.2.0
- PHP version: 8.2.15
- Database driver & version: MySQL 8.0.33

**Comment by i-just** [comment]
Hi, thanks for reporting! Based on my tests, this could have happened if the queue job to trigger customer data sync wasn’t completed before the next email update. I raised a PR for this.

**Comment by i-just** [comment]
Stripe 1.2.0 is out with that fix. Thanks again!
