### ISSUE TITLE
Listen to Webhook events

### ISSUE THREAD

**Issue by knufri** [craftcms/stripe#17]
### Description
I'm trying to figure out how to listen to the webhook events. The CheckoutSessionEvent works perfectly. But I would like to create a user in craft after successful subscription via module. I can't find anything in the documentation. Is there a way to react to the customer.subscription.created?

### Additional info

- Craft version: Craft Pro 5.2.8
- PHP version: 8.2.21
- Database driver & version: MySQL 8.0.33

**Comment by i-just** [comment]
Hi, thanks for reaching out! The Stripe plugin is already listening to the `customer.subscription.created` event (among others) and reacting to it. Technically, listening to the events from your plugin/module is already achievable, but you’d have to do it all yourself - create your own endpoint, listen and react. That being said, I think it makes sense for the plugin to provide an event you can tap into to take the hassle out of it. I just raised a PR for it.

**Comment by knufri** [comment]
Hello @i-just,

Many thanks for the quick reply and the associated PR. I really appreciate it. I'm looking forward to when the PR has been merged and I can test the extension. If I understand correctly, you can intercept all webhooks sent by Stripe via the event type?

Greetings Jan

**Comment by i-just** [comment]
Stripe 1.2.0 is out with that new event. Thanks again!
