### ISSUE TITLE
How to filter to only current subscriptions?

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/stripe#24]
I would expect

```
{% set subscription = currentUser.getStripeSubscriptions.status("active").all() %}
```

To show their active subscriptions, but it shows their cancelled status ones too.

Is there a way to request this, or would it be custom PHP to query it?

**Comment by i-just** [comment]
Hi, thanks for getting in touch.

The `getStripeSubscriptions()` method [returns a collection](https://github.com/craftcms/stripe/blob/1.1.0/src/behaviors/StripeCustomerBehavior.php#L90), so if you want to filter the results by their Stripe status, you can do so via: 
`{% set subscriptions = currentUser.getStripeSubscriptions().where('stripeStatus', 'active').all() %}`

I hope this helps!

**Comment by pimago** [comment]
Sorry for digging this out. And how would I filter for two conditions?
This doesn't seem to work:

`{% for price in product.prices.where(['and', ['stripeStatus', 'active'], ['data.recurring.interval', 'month']]).all() %}`

**Comment by i-just** [comment]
`product.prices` is a collection, so you need to chain your `where`s; for example: 
`{% for price in product.prices.where('stripeStatus', 'active').where('data.recurring.interval', 'month').all() %}`

**Comment by pimago** [comment]
Thank you! I tried that with andWhere
