### ISSUE TITLE
Setting up Webhooks

### ISSUE THREAD

**Issue by pimago** [craftcms/stripe#33]
### Description

I am having difficulties setting up webhooks.
I set up the Stripe CLI made it listen with stripe listen --forward-to https://my-craft-project.ddev.site/stripe/webhooks/handle
Added my signing secret to the .env file like this STRIPE_WH_KEY=whsec_4d…
Then the documentation says "and return to the Stripe → Settings in the control panel" to do what?

Now when I change a product price for example. I can see it's listening but I get 400 errors. Web logs say "Stripe webhook handler failed with message:No signatures found matching the expected signature for payload"

Also what is /stripe/webhooks for and do I need to set up a Hosted endpoint here? https://dashboard.stripe.com/test/webhooks
Are these two only for the production environment?

### Additional info

- Craft version: 5.4.9
- PHP version: 8.3.8
- Database driver & version: MySQL 8.0.36
- Plugins & versions: 1.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch.

Did you change the hostname to match where your project lives? If you go to Control Panel > Stripe > Settings, do you have the secret key, publishable key and webhook signing secret fields filled out correctly (as in matching what's in your Stripe Dashboard > Developers > API keys and then Webhooks)?

You don't need to set up a hosted endpoint for local development. That's going to be useful for environments beyond local dev (staging, production etc) and it's what the <Control Panel>/stripe/webhooks is for.

**Comment by pimago** [comment]
Thank you for the fast reply.
Yes the hostname is correct. And the secret key, publishable key match the ones in the Stripe Dashboard. Under Webhooks I do not have any keys, but I can see the local listener.
Syncing with Utilities > Stripe Sync All is working fine.

**Comment by i-just** [comment]
Great, thanks for confirming.

> Under Webhooks I do not have any keys, but I can see the local listener.

But you do have the webhook signing secret from the `stripe listen` command added under Control Panel > Stripe > Settings > Webhook Signing Secret?

**Comment by pimago** [comment]
Yes with  a Environment Variable.

**Comment by i-just** [comment]
The Control Panel > Utilities > Stripe Sync All doesn’t involve webhooks; it only uses the keys (secret and publishable). 
The “No signatures found matching the expected signature for payload” will be thrown by Stripe if the signature in the event header doesn’t match the one stored in the application. 

I can trigger the error you’re seeing if I add a type-o to the Webhook Signing Secret.

Are you sure you don’t have any rogue characters (e.g. invisible spaces, etc) in the `whsec_` string? Or a space before/after the value in the Webhook Signing Secret field?

**Comment by pimago** [comment]
For a test, I just ran stripe trigger payment_intent.succeeded
And it seems to work now. I can change a price on Stripe and I can see the changes in Craft.
