### ISSUE TITLE
Create account when subscription email is not registered

### ISSUE THREAD

**Issue by zalito12** [craftcms/stripe#41]
### Description

If I'm not missing anything, right now I can pay for a subscription without having an account, and no account will be created with the email provided to stripe.

Don't you think it would be a nice feature to let the plugin create and account? At least give the option in settings where you can decide if you want this beahvior or not.

Subscriptions without account has no sense. If I want to create an account after stripe subscription creation I must make my own plugin/module, I think there must be other people in this situation.

Would you accept a PR with this feature?

### Additional info

- Craft version: 5.4.9
- PHP version: 8.2.24
- Database driver & version:
- Plugins & versions:

**Comment by i-just** [comment]
Stripe 1.3.0 is out with a new `createUserIfMissing` setting. Thanks again!

**Comment by zalito12** [comment]
That's great! I just saw the PR, super clean, I'm a noob about craft and I don't know much about the apis.

What do you think about raising an event when user is created? So you can make some kind of actions like sending  an activation email.
May be this could be another setting?

I don't know what should be the best approach here. 

Thank you!

**Comment by i-just** [comment]
Craft has lots of events you can use, including some that get called after a User element gets saved (e.g. `craft\elements\User::EVENT_AFTER_SAVE`). 

You might want to have a look at [this page](https://craftcms.com/docs/5.x/extend/events.html) in the docs. About midway through that page, there's a very handy code generator tool that can help you figure out a good starting point for what you need.

I hope this helps!
