### ISSUE TITLE
Old data is not deleted

### ISSUE THREAD

**Issue by zalito12** [craftcms/stripe#42]
### Description

When working with test data you can clear all data from dashboard, but the plugin does not clear all the models from db when sync.
It happens with
- customers
- invoces
- 

### Steps to reproduce

1. Sync your data from stripe
2. Clear your test data
3. Sync again and old (non existing) invoces are not deleted from db

### Additional info

- Craft version: 5.4.9
- PHP version: 8.2
- Database driver & version: Mysql
- Plugins & versions: 1.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I just raised a PR that adds a CLI command to clear all the plugin's data, which can be used e.g. after deleting the test data in Stripe dashboard.

**Comment by zalito12** [comment]
Do you think this could happen in a production enviroment? Having duplicated subs it's very confusing

**Comment by i-just** [comment]
Stripe 1.3.0 is out with the new `stripe/data/reset` command.
