### ISSUE TITLE
Unable to import database

### ISSUE THREAD

**Issue by d-karstens** [craftcms/stripe#65]
### Description
Hi, we've encountered an issue when trying to import a database from our live site to our development environments, with the following error message

`ERROR 3105 (HY000) at line 3558: The value specified for generated column 'customerId' in table 'stripe_paymentmethoddata' is not allowed.`

We are able to get it working by using the `stripe/data/reset` command on the live site and then syncing, but this isn't ideal to do whenever we need to pull the database

Let me know if you need any more information

### Steps to reproduce

1. Export database from a site with Stripe information synced
2. Import to an environment where the same Stripe information doesn't exist

### Additional info

- Craft version: 5.5.3
- PHP version: 8.2.26
- Database driver & version: MySQL 8.0.33 on live, and MySQL 8.0.36 on development
- Plugins & versions: Stripe plugin version 1.3.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. I am able to trigger this error if I export data in a way that exports the generated columns, too (`customerId` column in the `stripe_paymentmethoddata` table is an example of a generated column). For example, if I export to a csv file and then import from it and map the `customerId` in the csv to the corresponding column in the database. The solution here is to ensure your export doesn’t include the generated columns. 

I hope this helps. 

I’ll close this now, but feel free to reply if you run into any further issues or if anything’s unclear.
